Repository quicwg/base-drafts, pull requests merged in 2021-05, with the labels that each got.

#4871 Tidy the XML
  Makefile
  xml2rfc-tidy.py
Labels: -http, -invariants, -qpack, -recovery, -tls, -transport, editorial

#4876 Make the notation sections consistent
  draft-ietf-quic-invariants.md
  draft-ietf-quic-transport.md
Labels: -invariants, -transport, editorial

#4853 Handshake packets aren't special
  rfc9002.md
Labels: -recovery, editorial

#4886 Update readme to point to new locations
  README.md
Labels: editorial

#4875 RPC text changes for -tls
  rfc9001.md
Labels: -tls, editorial

#4877 RPC text changes up to Section 10
  rfc9000.md
Labels: -transport, editorial

#4879 Second batch of changes for transport
  rfc9000.md
Labels: -transport, editorial

#4878 Final batch of text changes for transport
  rfc9000.md
Labels: -transport, editorial

#4881 References in transport
  draft-ietf-quic-http.md
  draft-ietf-quic-qpack.md
  rfc8999.md
  rfc9000.md
  rfc9001.md
  rfc9002.md
Labels: -transport, editorial

#4882 Get the case of stateless reset consistent
  rfc9000.md
Labels: -transport, editorial

#4885 Put CRYPTO_ERROR in the registry
  rfc9000.md
  rfc9001.md
Labels: -tls, -transport, editorial

#4893 Recovery RFCEditor #6
  rfc9002.md
Labels: -recovery

#4895 Rpc recovery
  rfc9002.md
Labels: -recovery, editorial

#4896 We need to reference RFC 2119 and 8174 separately
  rfc8999.md
  rfc9000.md
  rfc9001.md
  rfc9002.md
Labels: editorial

#4898 RFC Editor edits for Appendix A
  rfc9002.md
Labels: -recovery, editorial

#4901 Invariants: Say 'field' more
  rfc8999.md
Labels: -invariants, editorial

#4905 Add missing a; rewrap
  rfc9000.md
Labels: -transport, editorial

#4903 Add missing word 'packet' in recovery section 6.3
  rfc9002.md
Labels: -recovery, editorial

#4906 Missing edit; add 'the's
  rfc9000.md
Labels: -transport, editorial

#4907 Stuff missed in transport appendices
  rfc9000.md
Labels: -transport, editorial

#4908 entries are listed
  rfc9000.md
Labels: -transport, editorial

#4909 9000 mbishop diff review
  rfc9000.md
Labels: -transport, editorial

#4910 Prevent the use
  rfc9000.md
Labels: -transport, editorial

#4915 All the stuff in RFC 9002 we missed in a screaming rush
  rfc9002.md
Labels: -recovery, editorial

#4913 All the missing pieces in RFC 9000 that I found
  rfc9000.md
Labels: -transport, editorial

#4912 All the missing pieces in RFC 9001 that I found
  rfc9001.md
Labels: -tls, editorial

#4914 Add 'its' to invariants
  rfc8999.md
Labels: -invariants, editorial

#4916 Do the contacts by hand
  rfc9000.md
  rfc9001.md
  rfc9002.md
  xml2rfc-tidy.py
Labels: -recovery, -tls, -transport, editorial

#4917 Stuff from the RPC review of RFC 9000
  rfc8999.md
  rfc9000.md
  rfc9001.md
  rfc9002.md
Labels: -transport, editorial

#4918 RPC changes to 9002
  rfc9002.md
Labels: -recovery, editorial

#4919 Use zero-width spaces for the table
  rfc9000.md
Labels: -transport, editorial

#4920 ECN Counts; last fix
  rfc9000.md
Labels: editorial

#4921 DOES IT NEVER END?!?
  rfc9000.md
Labels: -transport, editorial
