Repository quicwg/base-drafts, pull requests merged in 2022-04, with the labels that each got.

#4982 QPACK Auth48 edits
  rfc9114.md
  rfc9204.md
Labels: editorial, -qpack

#4983 Merge singular and plural index entries
  rfc9114.md
Labels: editorial, -http

#4979 SETTINGS_ not SETTING_
  rfc9114.md
Labels: editorial, -http, -qpack

#4940 Negative base values are invalid
  rfc9204.md
Labels: design, -qpack
