Repository quicwg/base-drafts, pull requests merged in 2022-02, with the labels that each got.

#4954 Easy RFC Editor Questions
  rfc9114.md
Labels: editorial, -http

#4927 Fix typo in GOAWAY frame encoding
  rfc9114.md
Labels: editorial, -http

#4931 Recommend careful behavior around push streams
  rfc9114.md
Labels: -http

#4936 Reference the concept, not the header
  rfc9114.md
Labels: -http

#4937 Fix ASCII code for LF, NUL.
  rfc9114.md
Labels: editorial, -http

#4941 Specify CONNECT error handling bidirectionally
  rfc9114.md
Labels: design, -http

#4942 Clarify unknown unidirectional stream handling
  rfc9114.md
Labels: design, -http

#4957 Hardcode references to other RFCs in C430
  rfc9114.md
Labels: editorial, -http

#4959 Rearrange and rename to align with updated HTTP/2 spec
  rfc9114.md
Labels: editorial, -http
